### ISSUE TITLE
5.3 -- Create a Slideshow (slideshow.js)

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/jqfundamentals#6]
Solution at: https://github.com/segunadeleye/jqfundamentals/blob/master/exercises/Ex5/slideshow.js

**Comment by mkangia** [comment]
Segun, the code delivers the work pretty smoothly. We can work on its quality though and make it better. Please reconsider 1) naming like "getCurrentImagePosition" should be actually "setCurrentImagePosition" since we are setting the value there.
2) Plus, re consider some variable initialisation. Like:
  this.totalSlides;
  this.currentImagePosition;
  We are not setting any default value for it but adding it on our object. Is that necessary?
3) and try to find easier approach for setting slide number. Doing "nextSlide.prevAll().length" is pretty heavy an operation.

**Comment by segunadeleye** [comment]
#### Issues fixed.
- I replaced nextSlide.prevAll().length with nextSlide.index()
